[tool.taskipy.tasks]
run = "python app.py"
try = "python testeWindow.py"

[tool.ruff]
line-length = 80
exclude = [".venv", "data"]

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20

